#!/usr/bin/python3

import sys
import subprocess
import json

import math

API_key = "AIzaSyC0XPb0udk8HMMEa8PbYp_qZu7WONnGt3U"
num_max_result = "50"

#Currently, this function is not used.
#Example:
# print(convert_username_to_channel_id("GoogleDevelopers")) #=> "UC_x5XG1OV2P6uZZ5FSM9Ttw"
def convert_username_to_channel_id(username):

    command = [
        'curl',
        '-s',
        'https://www.googleapis.com/youtube/v3/channels?part=snippet&forUsername=' + username + '&key=' + API_key,
        '--header',
        'Accept: application/json',
        '--compressed',
    ]
    output = subprocess.check_output(command)
    json_dict = json.loads(output)

    return json_dict['items'][0]['id']

#"Uploaded Videos" is just a special kind of playlist (see |https://developers.google.com/youtube/v3/docs/playlistItems?authuser=1| for the detail).
#This function returns the id of the playlist which belongs to a channel specified by `id`.
#Example:
# print(get_uploaded_videos_playlist_id("username", "GoogleDevelopers")) #=> "UU_x5XG1OV2P6uZZ5FSM9Ttw"
# print(get_uploaded_videos_playlist_id("channel_id", "UC_x5XG1OV2P6uZZ5FSM9Ttw")) #same as above
def get_uploaded_videos_playlist_id(id_type, id):

    if (id_type == "username"):
        by_what = "forUsername=" + id
    elif (id_type == "channel_id"):
        by_what = "id=" + id
    else:
        print("The value of `id_type` is incorrect")
        return

    command = [
        'curl',
        '--silent',
        'https://www.googleapis.com/youtube/v3/channels?part=contentDetails&' + by_what + '&maxResults=' + num_max_result + '&key=' + API_key,
        '--header',
        'Accept: application/json',
        '--compressed',
    ]
    output = subprocess.check_output(command)
    json_dict = json.loads(output)

    if (json_dict['items'] == []):
        print("There exists no channel specified by [ {} ].".format(id))
        return

    return json_dict['items'][0]['contentDetails']['relatedPlaylists']['uploads']

#This function returns a list of ids of videos in a playlist specified by `playlist_id`.
#Right after a video id matches any element in `already_retrieved_video_id_list`, the function returns.
#In other words, the returned list only includes video ids which are scanned before the first match.
#Note that (if `already_retrieved_video_id_list` is empty) the first element of the list corresponds to the **latest** video.
#Per request, at most `num_max_result` ids can be got, thus this function may send multiple requests that takes a while.
#Example:
# print(get_all_video_id_in_playlist("UU_x5XG1OV2P6uZZ5FSM9Ttw", [])) #=> list of video ids
def get_all_video_id_in_playlist(playlist_id, already_retrieved_video_id_list, should_show_progress = False):

    video_id_list = []

    page_info = ""

    if (should_show_progress):
        num_total_result = 0
        num_page = 0

    i = -1

    while (True):

        i += 1

        command = [
            'curl',
            '--silent',
            'https://www.googleapis.com/youtube/v3/playlistItems?part=contentDetails' + page_info + '&maxResults=' + num_max_result + '&playlistId=' + playlist_id + '&key=' + API_key,
            '--header',
            'Accept: application/json',
            '--compressed'
        ]
        output = subprocess.check_output(command)
        json_dict = json.loads(output)

        if (i == 0 and not 'items' in json_dict):
            print("There exists no channel specified by [ {} ].".format(playlist_id))
            return

        if (should_show_progress):

            if (i == 0):
                num_total_result = int(json_dict['pageInfo']['totalResults'])
                num_page = math.ceil(num_total_result / int(num_max_result))

            if (num_page > 1):
                print("    [{}/{}] Done.".format(i + 1, num_page))

        for video in json_dict['items']:
            video_id = video['contentDetails']['videoId']
            if (video_id in already_retrieved_video_id_list):
                return video_id_list
            else:
                video_id_list.append(video_id)

        if ('nextPageToken' in json_dict):
            page_info = '&pageToken=' + json_dict['nextPageToken']
        else:
            break

    return video_id_list

#Example:
# print(get_video_title("5X13ZffwtjE")) #=> "Nina77「完全少女論」"
def get_video_title(video_id, should_append_uploaded_date = False):

    command = [
        'curl',
        '--silent',
        'https://www.googleapis.com/youtube/v3/videos?part=snippet&id=' + video_id + '&key=' + API_key,
        '--header',
        'Accept: application/json',
        '--compressed',
    ]
    output = subprocess.check_output(command)
    json_dict = json.loads(output)

    title = json_dict['items'][0]['snippet']['title']
    if (should_append_uploaded_date):
        title += "_" + json_dict['items'][0]['snippet']['publishedAt']

    return title

if (__name__ == "__main__"):

    usage_message = "Usage:\n\
  python3 " + sys.argv[0] + " <playlist spec> <output file name>\n\
\n\
<playlist spec>:\n\
  --username <user name>         specify all uploaded videos by <user name>\n\
  --channel-id <channel id>      specify all uploaded videos in <channel id>\n\
  --playlist-id <playlist id>    specify all videos in <playlist id>\
"

    if (len(sys.argv) != 4):
        print(usage_message)
        sys.exit(0)

    if (sys.argv[1] == "--username"):
        id_type = "username"
    elif (sys.argv[1] == "--channel-id"):
        id_type = "channel_id"
    elif (sys.argv[1] == "--playlist-id"):
        id_type = "playlist_id"
        playlist_id = sys.argv[2]
    else:
        print("Invalid option [ {} ] was passed.".format(sys.argv[1]))
        print(usage_message)
        sys.exit(1)

    already_retrieved_video_id_list = []
    try:
        with open(sys.argv[3], "r") as f_in:
            contents = f_in.readlines()
            for line in contents:
                video_id = line.split(' ')[0]
                if (video_id[0] == '#'):
                    video_id = video_id[1:]
                already_retrieved_video_id_list.append(video_id)
    except:
        pass

    if (id_type != "playlist_id"):
        print("Retrieving the playlist id...")
        playlist_id = get_uploaded_videos_playlist_id(id_type, sys.argv[2])
        if (playlist_id == None):
            sys.exit(1)

    print("Retrieving video ids...")
    video_id_list = get_all_video_id_in_playlist(playlist_id, already_retrieved_video_id_list, True)
    if (video_id_list == None):
        sys.exit(1)
    video_id_list.reverse() #Reverse the order so that the first element corresponds to the oldest video.

    if (len(video_id_list) == 0):
        print("No new video id is appended to [ {} ].".format(sys.argv[3]))
    else:
        print("Opening [ {} ]...".format(sys.argv[3]))
        try:
            with open(sys.argv[3], "a") as f_out:
                print("Appending {} new video ids to the file...".format(len(video_id_list)))
                for i in video_id_list:
                    f_out.write(i + " " + get_video_title(i, True) + "\n")
                print("Done.")
        except Exception as e:
            print(e)
            print("An error occured while opening [ {} ].".format(sys.argv[3]))
            sys.exit(1)

# vim: syntax=py

